# Generated by Django 3.2.22 on 2023-10-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='name',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='label',
        ),
    ]
