# Generated by Django 3.2.22 on 2023-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0002_auto_20231026_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='apple_music_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='credits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='performers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
