# Generated by Django 3.2.22 on 2023-10-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0004_album_tower_records_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
    ]
