# Generated by Django 3.2.22 on 2023-11-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0006_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
