# Generated by Django 3.2.22 on 2023-11-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0008_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
    ]
