# Generated by Django 3.2.22 on 2023-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_list', '0009_alter_album_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
